# Label configuration for the repository
# This file defines the labels that should exist in the repository

# Priority labels
- name: "priority: critical"
  color: "b60205"
  description: "Critical priority - needs immediate attention"

- name: "priority: high"
  color: "d93f0b"
  description: "High priority"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority"

# Type labels
- name: "type: bug"
  color: "d73a4a"
  description: "Something isn't working"
  aliases: ["bug"]

- name: "type: feature"
  color: "a2eeef"
  description: "New feature or request"
  aliases: ["feature", "enhancement"]

- name: "type: documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"
  aliases: ["documentation"]

- name: "type: refactor"
  color: "d4c5f9"
  description: "Code refactoring"

- name: "type: performance"
  color: "1d76db"
  description: "Performance improvements"

- name: "type: security"
  color: "b60205"
  description: "Security related changes"

# Component labels
- name: "component: frontend"
  color: "fef2c0"
  description: "Frontend related changes"
  aliases: ["frontend"]

- name: "component: backend"
  color: "c2e0c6"
  description: "Backend related changes"
  aliases: ["backend"]

- name: "component: api"
  color: "bfdadc"
  description: "API related changes"

- name: "component: database"
  color: "f9d0c4"
  description: "Database related changes"

- name: "component: ci/cd"
  color: "e4e669"
  description: "CI/CD pipeline changes"
  aliases: ["github-actions"]

- name: "component: dependencies"
  color: "0366d6"
  description: "Dependencies updates"
  aliases: ["dependencies"]

# Status labels
- name: "status: needs review"
  color: "fbca04"
  description: "Waiting for code review"

- name: "status: needs testing"
  color: "d4c5f9"
  description: "Needs testing"

- name: "status: blocked"
  color: "b60205"
  description: "Blocked by external dependency"

- name: "status: work in progress"
  color: "0052cc"
  description: "Currently being worked on"

- name: "status: ready to merge"
  color: "0e8a16"
  description: "Ready to be merged"

# Size labels
- name: "size: XS"
  color: "3cbf00"
  description: "Extra small changes (1-10 lines)"

- name: "size: S"
  color: "5d9801"
  description: "Small changes (11-50 lines)"

- name: "size: M"
  color: "7f7203"
  description: "Medium changes (51-200 lines)"

- name: "size: L"
  color: "a14c04"
  description: "Large changes (201-500 lines)"

- name: "size: XL"
  color: "c32505"
  description: "Extra large changes (500+ lines)"

# Special labels
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "invalid"
  color: "e4e669"
  description: "This doesn't seem right"

# Technology labels
- name: "tech: typescript"
  color: "326ce5"
  description: "TypeScript related"
  aliases: ["typescript"]

- name: "tech: javascript"
  color: "f1e05a"
  description: "JavaScript related"
  aliases: ["javascript"]

- name: "tech: react"
  color: "61dafb"
  description: "React related"

- name: "tech: nextjs"
  color: "000000"
  description: "Next.js related"

- name: "tech: nodejs"
  color: "68a063"
  description: "Node.js related"

- name: "tech: css"
  color: "563d7c"
  description: "CSS/Styling related"
  aliases: ["css"]
