---
name: Bug Report
description: Help us squash bugs by reporting issues
title: "Bug: "
labels: [bug, needs-triage]
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
        
        Thanks for helping us improve! Please provide as much detail as possible below.

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Category
      description: What type of bug is this?
      options:
        - UI/UX Issue
        - Functionality Bug
        - Performance Problem
        - Security Concern
        - Mobile Issue
        - Browser Compatibility
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-summary
    attributes:
      label: Brief Description
      description: Summarize the bug in one sentence
      placeholder: "The app crashes when..."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: How to Reproduce
      description: Step-by-step instructions to recreate the issue
      placeholder: |
        1. Open the app
        2. Navigate to...
        3. Click on...
        4. Observe the error
    validations:
      required: true

  - type: textarea
    id: actual-result
    attributes:
      label: What Happens
      description: Describe the actual behavior you're seeing
      placeholder: "Instead of working properly, the app..."
    validations:
      required: true

  - type: textarea
    id: expected-result
    attributes:
      label: What Should Happen
      description: Describe the expected correct behavior
      placeholder: "The app should..."
    validations:
      required: true

  - type: textarea
    id: environment-info
    attributes:
      label: Environment Details
      description: Tell us about your setup
      placeholder: |
        - Device: [e.g., iPhone 12, Windows PC]
        - OS: [e.g., iOS 15, Windows 11]
        - Browser: [e.g., Chrome 96, Safari 15]
        - App Version: [if applicable]
    validations:
      required: false

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages
      description: Any error messages, logs, or stack traces
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional Information
      description: Check all that apply
      options:
        - label: I can provide screenshots
        - label: I can provide a video recording
        - label: This happens consistently
        - label: This is a regression (worked before)
        - label: I've tried clearing cache/cookies
